a = "Ruby";
b = 10;
c = 34.2;
d = ["Olá"," Mundo"];
e = :Teste;
h = {curso: "Ruby", idioma: "pt-br", inicio: "Fevereiro 23"};
puts a;
puts d;
puts e;
puts h;
puts a.class;
puts b.class;
puts c.class;
puts d.class;
puts d[0];
puts e.class;
puts e.object_id;
puts e.class;
puts h[:curso];